---
- name: Include pretasks
  include_tasks: ../files/pretasks.yml
- name: install package with yum
  ansible.builtin.yum:
    name: '{{ item}}'
    state: present
  loop:
    - git
    - wget
  when: ansible_os_family in os_family_supported
- name: Generate index.html from template
  template:
    src: index.html.j2
    dest: /home/admin/index.html
- name: Create Apache container
  docker_container:
    name: "{{container_name}}"
    image: "{{container_image}}"
    state: started
    ports:
      - "{{container_port}}:80"
    volumes:
     - /home/admin/index.html:/usr/local/apache2/htdocs/index.html

